import { Router, type IRouter } from "express";
import authRouter from "../modules/auth/auth.routes";
import companyRouter from "../modules/companies/company.routes";
import userRouter from "../modules/users/user.routes";
import pipelineRouter from "../modules/pipeline/pipeline.routes";
import tagRouter from "../modules/tags/tag.routes";
import leadRouter from "../modules/leads/lead.routes";
import followUpRouter from "../modules/followups/followup.routes";
import activityRouter from "../modules/activity/activity.routes";
import landingPageRouter from "../modules/landing-pages/landing-page.routes";
import leadCaptureRouter from "../modules/lead-capture/lead-capture.routes";
import campaignRouter from "../modules/campaigns/campaign.routes";
import notificationRouter from "../modules/notifications/notification.routes";
import settingRouter from "../modules/settings/setting.routes";
import customFieldRouter from "../modules/custom-fields/custom-field.routes";
import leadSourceRouter from "../modules/lead-sources/lead-source.routes";
import leadStatusRouter from "../modules/lead-statuses/lead-status.routes";
import analyticsRouter from "../modules/analytics/analytics.routes";
import reportRouter from "../modules/reports/report.routes";
import searchRouter from "../modules/search/search.routes";
import profileRouter from "../modules/profile/profile.routes";
import roleRouter from "../modules/roles/role.routes";
import uploadRouter from "../modules/uploads/upload.routes";
import aiCallingRouter from "../providers/ai-calling/routes";
import whatsAppRouter from "../providers/whatsapp/routes";
import paymentsRouter from "../providers/payments/routes";
import imageGenerationRouter from "../providers/image-generation/routes";
import { apiRateLimiter } from "../middlewares/rateLimit";

const router: IRouter = Router();

router.use(apiRateLimiter);

router.use("/auth", authRouter);
router.use("/companies", companyRouter);
router.use("/users", userRouter);
router.use("/pipeline-stages", pipelineRouter);
router.use("/tags", tagRouter);
router.use("/leads", leadRouter);
router.use("/follow-ups", followUpRouter);
router.use("/activity-logs", activityRouter);
router.use("/landing-pages", landingPageRouter);
router.use("/lead-capture", leadCaptureRouter);
router.use("/campaigns", campaignRouter);
router.use("/notifications", notificationRouter);
router.use("/settings", settingRouter);
router.use("/custom-fields", customFieldRouter);
router.use("/lead-sources", leadSourceRouter);
router.use("/lead-statuses", leadStatusRouter);
router.use("/analytics", analyticsRouter);
router.use("/reports", reportRouter);
router.use("/search", searchRouter);
router.use("/profile", profileRouter);
router.use("/roles", roleRouter);
router.use("/storage", uploadRouter);
router.use("/providers/ai-calling", aiCallingRouter);
router.use("/providers/whatsapp", whatsAppRouter);
router.use("/providers/payments", paymentsRouter);
router.use("/providers/image-generation", imageGenerationRouter);

export default router;
